# Introduction to ScikitLearn (sklearn)

This notebook demonstrates some of the most useful functions of the beautiful Scikit-Learn library.

What we're going to cover



In [91]:
#let's Listify the contetns
what_were_coverging = [
    
    "0. An end-to-end Scikit-Learn workflow",
    "1. Getting the data Ready",
    "2. Chosse the right estimator/akigruthm for our problems",
    "3. fit the model;algorithm and use to it to make predicition",
    "4. Evaluating a model.",
    "5. Improver a model.",
    "6. Save and load a trainned model.",
    "7. Putting it all together!"]

In [90]:
#Standard import
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline


## 0. An end-to-end Scitkit-Learn Workflow

In [44]:
# 1. get data ready
import pandas as pd
heart_disease = pd.read_csv("../example/heart.csv")
heart_disease

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
0        0   0     1       1  
1        0   0     2       1  
2        2   0     2       1  
3        2   0     2       1  
4        2   0     2       1  
..     ...  ..   ...     ...  
298      1   0     3       0  
299      1   0     3       0  
300      1   2     3       0  
301      1   1     3       0  
302      1   1     2       0  

[303 rows x 14 columns]

In [45]:
#Create x (Feature matrix)
X = heart_disease.drop("target", axis=1)

#Create y (labels)

y = heart_disease["target"]


In [ ]:
import warnings
warnings.filterwarnings("ignore")

In [71]:
# 2. chosse the right model and hyperparamentesr
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier()

#We'll keep the default Hyperparameters

clf.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'auto',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_impurity_split': None,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

In [72]:
# 3. Fit the model to the training data
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [73]:
clf.fit(X_train, y_train);

In [74]:
X_train

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
70    54    1   2       120   258    0        0      147      0      0.4   
177   64    1   2       140   335    0        1      158      0      0.0   
284   61    1   0       140   207    0        0      138      1      1.9   
29    53    1   2       130   197    1        0      152      0      1.2   
71    51    1   2        94   227    0        1      154      1      0.0   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
50    51    0   2       130   256    0        0      149      0      0.5   
229   64    1   2       125   309    0        1      131      1      1.8   
37    54    1   2       150   232    0        0      165      0      1.6   
157   35    1   1       122   192    0        1      174      0      0.0   
237   60    1   0       140   293    0        0      170      0      1.2   

     slope  ca  thal  
70       1   0     3  
177      2   0     2  
284      2   1     3  
29       0   0     2  
71       2   1     3  
..     ...  ..   ...  
50       2   0     2  
229      1   0     3  
37       2   0     3  
157      2   0     2  
237      1   2     3  

[242 rows x 13 columns]

In [75]:
# Make a Prediction
#y_label = clf.predict(np.array([0,2,3,4]))

In [76]:
y_preds = clf.predict(X_test)
y_preds

array([0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0], dtype=int64)

In [77]:
y_test

186    0
101    1
131    1
129    1
106    1
      ..
198    0
242    0
24     1
275    0
235    0
Name: target, Length: 61, dtype: int64

In [78]:
# 4. Evaluate the model on the training data and test data
clf.score(X_train, y_train)

1.0

In [79]:
clf.score(X_test, y_test)

0.8852459016393442

In [80]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(classification_report(y_test, y_preds))

              precision    recall  f1-score   support

           0       0.90      0.87      0.88        30
           1       0.88      0.90      0.89        31

    accuracy                           0.89        61
   macro avg       0.89      0.88      0.89        61
weighted avg       0.89      0.89      0.89        61



In [81]:
confusion_matrix(y_test, y_preds)

array([[26,  4],
       [ 3, 28]], dtype=int64)

In [82]:
accuracy_score(y_test, y_preds)

0.8852459016393442

In [83]:
# 5. Imporve a model
# TRy different amount of n_estimators

np.random.seed(42)
for i in range(10, 100, 10):
    print(f"Trying model with {i} estimators...")
    clf = RandomForestClassifier(n_estimators=i).fit(X_train, y_train)
    print(f"Model Acuuracy on test set: {clf.score(X_test, y_test) * 100:.2f}%")
    print()
    

Trying model with 10 estimators...
Model Acuuracy on test set: 78.69%

Trying model with 20 estimators...
Model Acuuracy on test set: 85.25%

Trying model with 30 estimators...
Model Acuuracy on test set: 81.97%

Trying model with 40 estimators...
Model Acuuracy on test set: 86.89%

Trying model with 50 estimators...
Model Acuuracy on test set: 83.61%

Trying model with 60 estimators...
Model Acuuracy on test set: 83.61%

Trying model with 70 estimators...
Model Acuuracy on test set: 81.97%

Trying model with 80 estimators...
Model Acuuracy on test set: 86.89%

Trying model with 90 estimators...
Model Acuuracy on test set: 80.33%



In [84]:
# 6. Save a model and load it
import pickle

pickle.dump(clf, open("random_forst_model_1.pkl", "wb"))

In [85]:
loaded_model = pickle.load( open("random_forst_model_1.pkl", "rb"))
loaded_model.score(X_test, y_test)


0.8032786885245902

## 1. Getting the Data ready to be used with machine learning

Three main things we have to do:
    1. Split the data into features and labels (Usually ´X´ & ´y´)
    2. Filling (Also called imputing) or Disregarding missing values
    3. Converting nun-numeraical values to numerical values (also called feature encoding)

In [92]:
heart_disease.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [95]:
X = heart_disease.drop('target', axis=1)
X.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  
0   0     1  
1   0     2  
2   0     2  
3   0     2  
4   0     2

In [96]:
y = heart_disease['target']
y.head()

0    1
1    1
2    1
3    1
4    1
Name: target, dtype: int64

In [98]:
# Split the data into training and test Sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [99]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((242, 13), (61, 13), (242,), (61,))

In [102]:
x.shape[0] * 0.8

242.4

In [103]:
242+61

303

In [101]:
len(heart_disease)

303

### 1.1 Make Sure it's all numerical

In [120]:
car_sales = pd.read_csv("../Data/car-sales-extended.csv")
car_sales.head()

Make Colour  Odometer (KM)  Doors  Price
0   Honda  White          35431      4  15323
1     BMW   Blue         192714      5  19943
2   Honda  White          84714      4  28343
3  Toyota  White         154365      4  13434
4  Nissan   Blue         181577      3  14043

In [121]:
len(car_sales)

1000

In [122]:
car_sales.dtypes

Make             object
Colour           object
Odometer (KM)     int64
Doors             int64
Price             int64
dtype: object

In [124]:
# Split into x/y

X = car_sales.drop("Price", axis=1)
y= car_sales['Price']

# Split inot traning and test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)




In [108]:
# Build Machine learning model
from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor()
model.fit(X_train, y_train)
model.score(X_test, y_test)

ValueError: could not convert string to float: 'Honda'

In [114]:
# Turn the categories into numbers
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categorical_features = ["Make", "Colour", "Doors"]
one_hot = OneHotEncoder()
transformer = ColumnTransformer([("one_hot",
                                  one_hot,
                                  categorical_features)],
                                  remainder="passthrough")

transformed_X = transformer.fit_transform(X)
transformed_X


array([[0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 3.54310e+04],
       [1.00000e+00, 0.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        1.00000e+00, 1.92714e+05],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 8.47140e+04],
       ...,
       [0.00000e+00, 0.00000e+00, 1.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 6.66040e+04],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 2.15883e+05],
       [0.00000e+00, 0.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 2.48360e+05]])

In [117]:
X.head()

Make Colour  Odometer (KM)  Doors
0   Honda  White          35431      4
1     BMW   Blue         192714      5
2   Honda  White          84714      4
3  Toyota  White         154365      4
4  Nissan   Blue         181577      3

In [115]:
pd.DataFrame(transformed_X)

0    1    2    3    4    5    6    7    8    9    10   11        12
0    0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   35431.0
1    1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  192714.0
2    0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   84714.0
3    0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  154365.0
4    0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  181577.0
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...       ...
995  0.0  0.0  0.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0   35820.0
996  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  155144.0
997  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0   66604.0
998  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  215883.0
999  0.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  248360.0

[1000 rows x 13 columns]

In [118]:
dummies = pd.get_dummies(car_sales[["Make", "Colour", "Doors"]])
dummies

Doors  Make_BMW  Make_Honda  Make_Nissan  Make_Toyota  Colour_Black  \
0        4         0           1            0            0             0   
1        5         1           0            0            0             0   
2        4         0           1            0            0             0   
3        4         0           0            0            1             0   
4        3         0           0            1            0             0   
..     ...       ...         ...          ...          ...           ...   
995      4         0           0            0            1             1   
996      3         0           0            1            0             0   
997      4         0           0            1            0             0   
998      4         0           1            0            0             0   
999      4         0           0            0            1             0   

     Colour_Blue  Colour_Green  Colour_Red  Colour_White  
0              0             0           0             1  
1              1             0           0             0  
2              0             0           0             1  
3              0             0           0             1  
4              1             0           0             0  
..           ...           ...         ...           ...  
995            0             0           0             0  
996            0             0           0             1  
997            1             0           0             0  
998            0             0           0             1  
999            1             0           0             0  

[1000 rows x 10 columns]

In [127]:
# Let's refit the model
np.random.seed(42)
X_train, X_test, y_train, y_test = train_test_split(transformed_X, 
                                                    y , 
                                                    test_size=0.2)
model.fit(X_train, y_train);

In [129]:
model.score(X_test,y_test)

0.3235867221569877